defaults: &defaults
  working_directory: /home/circleci/app
  docker:
    - image: node:carbon

version: 2
jobs:
  "check dependencies":
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Check for security advisories
          command: npm run snyk

      - run:
          name: Generate Build version
          command: echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV

      - run:
          name: Record build info
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              GIT_REF=$CIRCLE_SHA1 BUILD_NUMBER=$CIRCLE_BUILD_NUM \
              npm run record-build-info
            fi

      - persist_to_workspace:
          root: .
          paths:
            - .

  "run tests":
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/app/

      - run:
          name: Run Unit Tests
          command: |
            npm run test-report
          environment:
            MOCHA_FILE: build/junit/test-results.xml

      - store_test_results:
          path: build

  "generate coverage":
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/app/

      - run:
          name: Run Coverage Tests
          command: |
            npm run test-coverage
          environment:
            LCOV_FILE: coverage/lcov.info

      - store_artifacts:
          path: coverage/lcov-report

  "generate documentation":
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/app/

      - run:
          name: Dredd Tests
          command: |
            npm run docs-test

  "schedule deployment":
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/app/

      - deploy:
          name: Build Derived Git Commit
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config user.name "Circle CI"
              git config user.email "circle@circleci.com"

              git add --force --verbose build-info.json

              git commit \
                -m "Deployment of build $CIRCLE_BUILD_NUM" \
                -m "$(git log --format=%B -n 1 $CIRCLE_SHA1)" \
                -m "From gitref $CIRCLE_SHA1"
            fi

      - deploy:
          name: Deploy to Dev environment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push --force origin HEAD:deploy-to-dev
            fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - "check dependencies":
          filters:
            branches:
              ignore: /deploy-to.*/
            tags:
              ignore: /.*/
      - "run tests":
          requires:
            - "check dependencies"
      - "generate coverage":
          requires:
            - "run tests"
      - "generate documentation":
          requires:
            - "check dependencies"
      - "schedule deployment":
          requires:
            - "run tests"
            - "generate documentation"
